# Just a label at present
environment: dev

# Flag to handle the type of infrastructure running on. Currently handles minikube, with placeholders for AKS.
context: minikube

# Additional context-specific settings
minikube:
  node_port_http: 30080
  node_port_https: 30443

# Opal configuration
opal:
  env_vars:
    OPAL_ADMINISTRATOR_PASSWORD: P@55w0rd
    CSRF_ALLOWED: datashield1.liv.ac.uk,landertre-dev.org 
    org_obiba_opal_https_port: '"-1"'
  demo:
    OPAL_DEMO_USER_NAME: bob
    OPAL_DEMO_USER_PASSWORD: P@55w0rd1
    OPAL_DEMO_PROJECT: DEMO
    OPAL_DEMO_TABLE: CNSIM1
    OPAL_DEMO_SOURCE_DATA_URL: https://raw.githubusercontent.com/datashield/dsBaseClient/master/tests/testthat/data_files/CNSIM/CNSIM1.csv
  
# MySQL configuration
mysql:
  env_vars:
    MYSQLDATA_DATABASE: dsdb
    MYSQLDATA_PASSWORD: P@55w0rd
    MYSQLDATA_USER: dsuser
