agate:
  image: obiba/agate:2.8
  env:
    AGATE_ADMINISTRATOR_PASSWORD: "p@55w0rd"

mysqldb:
  image: mysql:9.0.1
  administrator_password:
    secret: ""
    key: "mysql-administrator-password"
  env:
    MYSQLDATA_DATABASE: "dsdb"
    MYSQLDATA_USER: "dsdb_user"
    MYSQLDATA_PASSWORD: "p@55w0rd"
    # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  pvc:
    storage: 1Gi

mongodb:
  image: mongo:4.4.18
  port: 27017
  pvc:
    storage: 1Gi

opal:
  replicaCount: 1
  image: obiba/opal:4.7.4
  pullPolicy: IfNotPresent
  env:
    OPAL_ADMINISTRATOR_PASSWORD: "p@55w0rd"
    CSRF_ALLOWED: "ingress.local"
    ORG_OBIBA_OPAL_HTTPS_PORT: "-1"
  service:
    type: ClusterIP
    port: 80
  pvc:
    storage: 1Gi

  demo:
    OPAL_DEMO_USER_NAME: dsuser
    OPAL_DEMO_USER_PASSWORD: P@ssw0rd
    OPAL_DEMO_PROJECT: CNSIM
    OPAL_DEMO_TABLE: CNSIM99
    OPAL_DEMO_SOURCE_DATA_URL: https://raw.githubusercontent.com/OllyButters/ds_data/main/CNSIM/CNSIM1.csv
    OPAL_COHORT_PROJECT: COHORT
    OPAL_COHORT_TABLE: conditions1
    OPAL_COHORT_SOURCE_DATA_URL: https://raw.githubusercontent.com/OllyButters/ds_data/main/synthea/conditionsa.csv

rock:
  replicatCount: 1
  image: obiba/rock:2.1.0
  env:
    ROCK_ADMINISTRATOR_NAME: admin
    ROCK_ADMINISTRATOR_PASSWORD: p@55w0rd
    ROCK_MANAGER_NAME: manager
    ROCK_MANAGER_PASSWORD: p@55w0rd
    ROCK_USER_NAME: user
    ROCK_USER_PASSWORD: p@55w0rd
