apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "datashield.opal.name" . }}
  labels:
    app: {{ include "datashield.opal.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  tls:
    - hosts:
      - ingress.local
      secretName: tls-secret-ingress-local
  ingressClassName: nginx
  rules:
  - host: ingress.local
    http:
      paths:
      - path: /opal(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "datashield.opal.name" . }}
            port:
              name: http
