apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: rock
  name: rock
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rock
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: rock
    spec:
      containers:
        - image: datashield/rock-base:latest
          name: rock
          ports:
            - containerPort: 8085
          resources: {}
      restartPolicy: Always