apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ include "datashield.agate.name" . }}
  name: {{ include "datashield.agate.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "datashield.agate.name" . }}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ include "datashield.agate.name" . }}
    spec:
      containers:
        - name: agate
          image: {{ .Values.agate.image }}
          {{ if .Values.agate.resources }}
          resources: 
            {{- .Values.agate.resources | nindent 12}}
          {{ end }}
          env:
            - name: AGATE_ADMINISTRATOR_PASSWORD
              value: {{ .Values.agate.env.AGATE_ADMINISTRATOR_PASSWORD }}
            - name: MONGO_HOST
              value: {{ include "datashield.mongodb.name" . }}
            - name: MONGO_PORT
              value: "27017"
            - name: RECAPTCHA_SITE_KEY
              value: http://opal:8080
            - name: RECAPTCHA_SECRET_KEY
              value: http://agate:8081
      restartPolicy: Always
