apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-volume-1
spec:
  {{- if eq .Values.context "minikube"}}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/k8s/pvs/mongo1"
  {{- else if eq .Values.context "AKS"}}
  #
  # PLACEHOLDER FOR AKS PersistentVOLUME
  #
  {{- end}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage-claim-1
  labels:
    name: mongo-storage-claim-1
    environment: {{ .Values.environment }}
    context: {{ .Values.context }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-storage-volume-1
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual
