apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldata-deployment
  labels:
    name: mysqldata-deployment
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldata-deployment
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        app: mysqldata-deployment
        environment: {{ .Values.environment }}
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.env_vars.MYSQLDATA_DATABASE }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.env_vars.MYSQLDATA_PASSWORD }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.env_vars.MYSQLDATA_USER }}
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "TRUE"
          image: mysql
          name: mysqldata
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          resources: {}
      restartPolicy: Always
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-storage-claim-1
