apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: mysqldata
  name: mysqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldata
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: mysqldata
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dsdb
            - name: MYSQL_PASSWORD
              value: P@55w0rd
            - name: MYSQL_USER
              value: dsuser
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "TRUE"
          image: mysql
          name: mysqldata
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
