apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-deployment
  labels:
    name: rock-deployment
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rock-deployment
  template:
    metadata:
      annotations: {}
      labels:
        app: rock-deployment
        environment: {{ .Values.environment }}
    spec:
      containers:
        - image: datashield/rock-base:latest
          name: rock
          ports:
            - containerPort: 8085
          resources: {}
      restartPolicy: Always